baseURL = 'https://example.org/'
languageCode = 'fr-fr'
title = 'Mon Carnet Naturaliste'
theme = 'hugo-theme-cleanwhite'

[params]
  header_image = "img/home-bg.jpg"
  slogan = "Observations botaniques et paysagères"
  title = "Héloïse Nature"
